"""initial schema — nodes, node subtypes, edges

Revision ID: 30c9b518252d
Revises:
Create Date: 2026-08-01

Hand-written rather than autogenerated (no live DB was available while
scaffolding this project), but it was checked by compiling the SQLAlchemy
models to Postgres DDL and diffing against these statements — see
backend/tests/test_models.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30c9b518252d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "nodes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("node_type", sa.String(32), nullable=False),
        sa.Column("is_entry_point", sa.Boolean(), nullable=False),
        sa.Column("is_crown_jewel", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_nodes_node_type", "nodes", ["node_type"])

    op.create_table(
        "assets",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("name", sa.String(512), nullable=False),
        sa.Column("asset_type", sa.String(32), nullable=False),
        sa.Column("in_scope", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
    )
    op.create_index("ix_assets_name", "assets", ["name"])

    op.create_table(
        "accounts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("username", sa.String(256), nullable=False),
        sa.Column("privilege_level", sa.String(16), nullable=False),
    )

    op.create_table(
        "data_stores",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("data_classification", sa.String(16), nullable=False),
        sa.Column("record_count_estimate", sa.Integer(), nullable=True),
    )

    op.create_table(
        "endpoints",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("path", sa.String(2048), nullable=False),
        sa.Column("method", sa.String(16), nullable=False),
        sa.Column("params", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("requires_auth", sa.Boolean(), nullable=True),
        sa.Column("documented", sa.Boolean(), nullable=False),
    )

    op.create_table(
        "findings",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("title", sa.String(512), nullable=False),
        sa.Column("cwe", sa.String(32), nullable=True),
        sa.Column("owasp_category", sa.String(128), nullable=True),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("exploit_public", sa.Boolean(), nullable=False),
        sa.Column("auth_required", sa.Boolean(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("status", sa.String(16), nullable=False),
    )

    op.create_table(
        "services",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(16), nullable=False),
        sa.Column("banner", sa.Text(), nullable=True),
        sa.Column("tech_stack", postgresql.ARRAY(sa.String()), nullable=False),
    )

    op.create_table(
        "web_applications",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("base_url", sa.String(1024), nullable=False),
        sa.Column("tech_stack", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("auth_type", sa.String(64), nullable=True),
    )

    # depends on findings (obtained_via_finding_id FK), so created after it
    op.create_table(
        "credentials",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("cred_type", sa.String(32), nullable=False),
        sa.Column("scope", sa.String(256), nullable=True),
        sa.Column(
            "obtained_via_finding_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("findings.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )

    op.create_table(
        "edges",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "source_node_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "target_node_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("nodes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("edge_type", sa.String(32), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("edge_metadata", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_edges_source_node_id", "edges", ["source_node_id"])
    op.create_index("ix_edges_target_node_id", "edges", ["target_node_id"])


def downgrade() -> None:
    op.drop_table("edges")
    op.drop_table("credentials")
    op.drop_table("web_applications")
    op.drop_table("services")
    op.drop_table("findings")
    op.drop_table("endpoints")
    op.drop_table("data_stores")
    op.drop_table("accounts")
    op.drop_table("assets")
    op.drop_table("nodes")
